# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_location_photo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo_category',
            field=models.CharField(default='', max_length=40),
        ),
    ]
