# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_category_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo_category',
            field=models.CharField(max_length=40),
        ),
    ]
